-- setting files
require("cafebabe.settings.remap")
require("cafebabe.settings.options")
require("cafebabe.settings.netrw")

-- initialize lazy
require("cafebabe.init_lazy")

-- initialize utility functions
require("cafebabe.utils.scratch_buffer")
require("cafebabe.utils.autocommands")

-- load plugins
require("cafebabe.plugins.luasnip")
require("cafebabe.plugins.colors")
require("cafebabe.plugins.dashboard")
require("cafebabe.plugins.telescope")
require("cafebabe.plugins.treesitter")
require("cafebabe.plugins.harpoon")
require("cafebabe.plugins.undotree")
require("cafebabe.plugins.git")
require("cafebabe.plugins.lspsignature")
require("cafebabe.plugins.lsp")
require("cafebabe.plugins.autopairs")
require("cafebabe.plugins.toggleterm")
require("cafebabe.plugins.troubleconf")
require("cafebabe.plugins.whichkey")
require("cafebabe.plugins.biscuits")
require("cafebabe.plugins.windows")
require("cafebabe.plugins.formatting")
require("cafebabe.plugins.lazyluadev")
require("cafebabe.plugins.filexplorer")
require("cafebabe.plugins.navic")
require("cafebabe.plugins.lualine")
require("cafebabe.plugins.miniai")
require("cafebabe.plugins.org")
require("cafebabe.plugins.focusconf")
require("cafebabe.plugins.dap")
require("cafebabe.plugins.comment")
require("cafebabe.plugins.hlchunk")
require("cafebabe.plugins.dressing")
require("cafebabe.plugins.rainbow")
require("cafebabe.plugins.screenkeys")
require("cafebabe.plugins.luasnip")
require("cafebabe.plugins.noice")
